---

ipfs_user: ipfs
priveos_user: priveos
encryption_service_user: encryptionservice

priveos_repo: "https://{{git_username}}:{{git_password}}@github.com/rawrat/privEOS.git"
priveos_install_dir: "/home/{{ priveos_user }}/privEOS/"
version: master

encryption_service_repo: https://{{git_username}}:{{git_password}}@github.com/rawrat/priveos-encryption-service.git
encryption_service_install_dir: "/home/{{ encryption_service_user }}/priveos-encryption-service/"

ansible_user: root
# Use these settings for non standard ssh port and/or ssh key
# ansible_ssh_private_key_file: ~/.ssh/key.pem
# ansible_port: 4567
