---
# Please edit the variables in this file 

chains:
  # First chain
    # Enter your EOS account that you're using to regnode with privEOS
  - nodeAccount: "You Producer EOS Account"
    # Which chain are we connecting to?
    httpEndpoint: "https://your_favourite_api_endpoint"
    # Chain ID e.g. ("e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473" for Jungle2)
    chainId: "EOSIO Chain ID"
    # The public key here is identical to the one you're using to regnode (see https://github.com/rawrat/privEOS#registering-your-node)
    publicKey: ""
    # Please follow the instructions here: https://github.com/rawrat/privEOS#add-watchdog-permission
    # And insert your watchdog private key here:
    watchdogPrivateKey: ""
    watchdogPermissionName: "watchdog"
    # The EOS Account name where the privEOS contract is deployed (e.g. priveosrules)
    contract: "priveosrules"
    # The name of your local mongodb database. Needs to be unique for every chain.
    dbName: "jungletestnet"
  # Second chain (if you want to connect to a second chain)
  # - nodeAccount: ""
  #   httpEndpoint: ""
  #   chainId: ""
  #   publicKey: ""
  #   watchdogPrivateKey: ""
  #   watchdogPermissionName: "watchdog"
  #   contract: "priveosrules"
  #   dbName: ""

# email address to be notified about the free let's encrypt SSL certificate
lets_encrypt_email: "your_email@example.com"

# Please provide your github credentials so we can check out private repos
git_username: "your_github_username"
git_password: "your_github_password"

# The host name that will be publicly visible. A DNS record must point to
# the IP address of the server we're going to use this on.
host_name: "my.server.name"

# The user the we're using to login to the server
# If it's not root, this user should have sudo power without a password
ansible_user: root

# Use these settings for non standard ssh port and/or ssh key
# ansible_ssh_private_key_file: ~/.ssh/key.pem
# ansible_port: 4567