---
# Please edit the variables in this file 

# Enter your EOS account that you're using to regnode with privEOS
nodeAccount: "You Producer EOS Account"

# Which chain are we connecting to?
httpEndpoint: "EOSIO Endpoint"
chainId: "EOSIO Chain ID"

# email address to be notified about the free let's encrypt SSL certificate
lets_encrypt_email: your_email@example.com

# Please provide your github credentials so we can check out private repos
git_username: your_github_username
git_password: your_github_password

# The host name that will be publicly visible. A DNS record must point to
# the IP address of the server we're going to use this on.
host_name: my.server.name

ansible_user: root

# Use these settings for non standard ssh port and/or ssh key
# ansible_ssh_private_key_file: ~/.ssh/key.pem
# ansible_port: 4567